### ISSUE TITLE
Broken in beta10 with fatal PHP error

### ISSUE THREAD

**Issue by rootwork** [ueberbit/addressfield#7]
With the beta10 update, any entity type that has an address field will give you a fatal error on its edit form:

```
( ! ) Fatal error: Call to undefined function Drupal\addressfield\Plugin\AddressfieldFormat\element_children() in /var/www/site/docroot/modules/contrib/addressfield/src/Plugin/AddressfieldFormat/Address.php on line 479
```

The last three items in the stack trace are:

```
22  0.7290  12162440    Drupal\Core\Field\WidgetBase->formSingleElement( )  ../WidgetBase.php:183
23  0.7291  12163624    Drupal\addressfield\Plugin\Field\FieldWidget\AddressFieldStandardWidget->formElement( ) ../WidgetBase.php:318
24  0.7955  12500072    Drupal\addressfield\Plugin\AddressfieldFormat\Address->format( )    ../AddressFieldStandardWidget.php:121
```

You also get a fatal error when you try to delete the field -- and while it's removed from the list of fields for the entity type, the table is still there in the database.

And you get a fatal error when you try to create a new address field:

```
( ! ) Fatal error: Call to undefined function element_children() in /var/www/site/docroot/modules/contrib/addressfield/addressfield.module on line 121
```

The last three items in the stack trace are:

```
18  0.3548  11274032    call_user_func_array:{/var/www/site/docroot/core/lib/Drupal/Core/Form/FormBuilder.php:766} ( )  ../FormBuilder.php:766
19  0.3548  11281176    addressfield_process_format_form( ) ../FormBuilder.php:766
20  0.3548  11284464    _addressfield_process_format_form( )    ../addressfield.module:116
```

Things were working fine in beta9, so I assume it has something to do with what changed in that update.

**Comment by webflo** [comment]
@rootwork Fixed it, please try again and open an issue if you find other bugs ... Thanks!

**Comment by rootwork** [comment]
Wow, that was some fast work! Yep, that fixed it. Thanks!
